### ISSUE TITLE
QueryParams.index is a long, should be BigInteger

### ISSUE THREAD

**Issue by spencergibb** [Ecwid/consul-api#10]
According to https://github.com/hashicorp/consul/blob/master/api/event.go#L90-L104 the watch index is a u64 which in java translates to BigInteger.  Longs are signed 63 bit numbers.  Another option is Guava's UnsignedLong.  Also affects `DefaultHttpTransport`.

**Comment by vgv** [comment]
Yep, I thought about it while write this code but decide do not use BigInteger.

1) Of course, you are correct and consul uses u64 which doesn't equal to Java long. This is a problem in theory, but in practice I do not think that any consul installation will overflow Long.MAX_VALUE

2) I think that primitive long is much easier to use than BigInteger field.

So, I decided to use long. Do you think that we *really* need to change long to BigInteger?

**Comment by spencergibb** [comment]
I am using the event services, and I have to convert the eventId to the last index so I can filter events.  It can only be done using BigInteger. If you have a negative number you will see problems.

**Comment by vgv** [comment]
Fixed in #51
