### ISSUE TITLE
java.net.SocketTimeoutException when blocking on API

### ISSUE THREAD

**Issue by duncanscott** [Ecwid/consul-api#125]
The default timeout for a blocking call against the Consul API is supposed to be 5 minutes:
[https://www.consul.io/api/index.html#blocking-queries](https://www.consul.io/api/index.html#blocking-queries)

But a blocking query against the API times out after a max of 1 minute with a java.net.SocketTimeoutException.   When performing a blocking query the SocketTimeoutException should not be thrown while the API call is still blocking.

This stackoverflow dialog appears to point to a solution:
[https://stackoverflow.com/questions/6024376/apache-httpcomponents-httpclient-timeout](https://stackoverflow.com/questions/6024376/apache-httpcomponents-httpclient-timeout)

**Comment by vgv** [comment]
Default read timeout is increased up to 10 minutes.
