### ISSUE TITLE
how to connect a consul cluster?

### ISSUE THREAD

**Issue by Jaware** [Ecwid/consul-api#137]
the api is as follows:
ConsulClient client = new ConsulClient("localhost");
if the "localhost" died,the client will be died too? is there any other way like 1ip:8500,2ip:8500,2ip:8500 to prevent single point failure?

**Comment by spencergibb** [comment]
The recommended way is to connect to an agent which handles the cluster connection

**Comment by vgv** [comment]
Of course, you can connect to any consul server in the network on any port:

`
ConsulClient client = new ConsulClient("consul-server.internal.network", 2313);
`

However, as @spencergibb says, the general approach is to connect to local consul.

**Comment by vgv** [comment]
Moreover, this is the general way to use consul. You should have the consul agent on every server in your network, so, it is not hard to connect to 'localhost'

**Comment by Jaware** [comment]
thanks for your reply.but i use docker,you mean i have to start a consul client(or server?) in my java docker container? @vgv

**Comment by vgv** [comment]
@Jaware 

It depends, but usually (in docker world) people have one container with consul per server. All other containers on this server connect to that one.

**Comment by vgv** [comment]
@Jaware 

For network you have at least two options:
1) You can do some network magic in docker and all your services will see the consul container as localhost. In this case you change nothing, all of your ConsulClient's connect to localhost.

2) You do not make any network bridges between consul container and app containers and just connect to consul agent using its own host/IP from all app containers.

**Comment by Jaware** [comment]
thanks ,i guess i have to choose the second one,but the pain is that when the host died,my app died too😭

**Comment by vgv** [comment]
Why do you need this? 
The host is down => the consul agent on this host is down too => all other servers/services in your cluster know that that host is down and ALL services on this host is down too. 

Consul handles this automatically out of the box.

**Comment by Jaware** [comment]
the node i mean is one of the consul node, may be it is the consul 's design problem....that issue is still open https://github.com/hashicorp/consul/issues/3473
