### ISSUE TITLE
Allow using a docker health check in the inner class check of a NewService

### ISSUE THREAD

**Issue by deuch** [Ecwid/consul-api#138]
Hello,

When i register a service, i can only choose TCP, HTTP, TTL, script only i nthe check definition of a service.
Can you please implement the Docker Health Check type as well ?
It's possible to do that in a 2 steps process (register the service and after the check) but the ACL related to the token must have node:write policy and it's not secure at all.

Be able to register a container check directly in the embedded check of a service let us to only put the service:write ACL only (and maybe node:read).
And if some service fail to start, some heakth check become agent health check and not service health check. And it causes some issues ...

**Comment by peka45** [comment]
I opened the pull requests #168 for this case.

**Comment by vgv** [comment]
Will be available in 1.4.2 in next few days
