### ISSUE TITLE
ConsulException should not be derived from RuntimeException

### ISSUE THREAD

**Issue by dickschoeller** [Ecwid/consul-api#140]
It is a really bad design practice to throw unchecked exceptions. It leads consumers to assume that there is no exception handling necessary or to be unclear about the types of exceptions that should be caught.

**Comment by vgv** [comment]
Hi, thank you for you report

I really think that this is an API design question. There is no one right answer should exceptions be checked or not.

In any case, we can't change supertype for ConsulException, it will break the backward compatibility and all usages of consul-api.
