### ISSUE TITLE
Add support for Header

### ISSUE THREAD

**Issue by johnBgood** [Ecwid/consul-api#148]
In the Consul documentation for Checks, there is a Description field which can contain a [Header](https://github.com/hashicorp/consul/blob/e748c63fff71dade428d4e34de72db575f590ee3/agent/structs/check_definition.go) attribute (useful for adding headers for instance).
Can this field be added ?

**Comment by johnBgood** [comment]
The commit concerns NewCheck, but what about the NewService.Check class ?

**Comment by vgv** [comment]
> The commit concerns NewCheck, but what about the NewService.Check class ?

Will fix in #162
