### ISSUE TITLE
/v1/catalog/service/<service> support?

### ISSUE THREAD

**Issue by BrentVukmer** [Ecwid/consul-api#15]
I haven't figured out how ConsulClient exposes querying a service in a datacenter for which nodes support it.

**Comment by zanella** [comment]
Like this?

            ConsulClient client = new ConsulClient("localhost");

            com.ecwid.consul.v1.Response<Map<String, List<String>>> resp = client.getCatalogServices(new QueryParams("dc1"));
            Map<String, List<String>> servicesMap = resp.getValue();

            for (String key : servicesMap.keySet()) {
                System.out.println(
                    String.format("{Service: {Name: [%s], Tags: %s}} -> %s",
                            key, servicesMap.get(key),
                            client.getCatalogService(key, null).getValue().get(0).toString()
                    )
                );
            }

**Comment by BrentVukmer** [comment]
Thanks.   That works for the "consul" service instance on my laptop, but not for the test service I registered programmatically (see #16).

**Comment by BrentVukmer** [comment]
Closing, may submit a PR with Javadoc links to the Consul API docs.
