### ISSUE TITLE
Deregistering a service instance - fails in test

### ISSUE THREAD

**Issue by BrentVukmer** [Ecwid/consul-api#16]
The following test code fails:

````
        NewService service = new NewService();
        service.setAddress("10.20.30.40");
        service.setPort(99);
        service.setId("test-service-1");
        service.setName("Test Service");
       ConsulClient client = new ConsulClient("localhost");
        client.agentServiceRegister(service);
       QueryParams dcQueryParams = new QueryParams("dc1");
        Response<Map<String, List<String>>> servicesResponse =      client.getCatalogServices(dcQueryParams);
        assertThat(servicesResponse.getValue().keySet().size(), equalTo(2));
        assertThat(servicesResponse.getValue().keySet(), hasItem("Test Service"));

        client.agentServiceDeregister("test-service-1");
        servicesResponse = client.getCatalogServices(dcQueryParams);
        assertThat(servicesResponse.getValue().keySet().size(), equalTo(1));
        assertThat(servicesResponse.getValue().keySet(), not(hasItem("Test Service")));
````

**Comment by vgv** [comment]
Hi

I've tried to reproduce this on latest consul 0.5.2 and all tests have passed. 
I really have 2 services after register (consul and Test Service) and only 1 service after deregistration (only consul).

**Comment by BrentVukmer** [comment]
Thanks for taking a look.   I'm also running against consul 0.5.2.  If this is an issue at all, it's an issue with consul.   

I started consul via: ```` consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul````

I ran this: ````curl -v 127.0.0.1:8500/v1/agent/service/deregister/Test%20Service````

And saw this in the console output for the consul instance: ````   2015/06/01 09:21:36 [INFO] agent: Deregistered service 'Test Service'````

But when I then run ````curl 127.0.0.1:8500/v1/catalog/services```` I still see an entry for 'Test Service`.

**Comment by vgv** [comment]
> If this is an issue at all, it's an issue with consul.

I think so. 
Consul-api doesn't use some 'consul magic', I just invoke Consul HTTP API to register/deregister services

**Comment by brentvukmer** [comment]
I think that the space in the name is the problem, FIY.
