### ISSUE TITLE
The meta Setting is not work ?

### ISSUE THREAD

**Issue by seifeHu** [Ecwid/consul-api#166]
I use meta in myCode 
		HashMap<String,String> meta2 = new HashMap<String,String>();
		meta2.put("weight", "50");
		newService2.setMeta(meta2);

            client.agentServiceRegister(newService2);

when I got health services  from agent  . I not got my setting meta .  
also . I use curl not got my setting meta 

http://127.0.0.1:8500/v1/health/service/my-service

Is it a bug ?

**Comment by vgv** [comment]
This has been fixed in #170 
The 1.4.2 release will be available in next couple days
