### ISSUE TITLE
Cannot register script health check on service

### ISSUE THREAD

**Issue by pparthenhs** [Ecwid/consul-api#171]
Hello to everyone, 

I am using the current library (1.4.1) as a maven dependency, also I am using consul version 1.3. But I cannot register script Health check on service.

My code was working on consul version 1.0.7, and using the library version 1.4.0
```
        NewService.Check serviceCheck = new NewService.Check();
        serviceCheck.setScript("docker exec mysql  mysqladmin -uroot -pxUNvbFUbHvv6hnkrTg86g7fXe87W9fTg status");
        serviceCheck.setInterval("30s");
``` 

But now I am getting 
```
Exception in thread "main" OperationException{statusCode=400, statusMessage='Bad Request', statusContent='Invalid check: TTL must be > 0 for TTL checks'}
	at com.ecwid.consul.v1.agent.AgentConsulClient.agentServiceRegister(AgentConsulClient.java:278)
	at com.ecwid.consul.v1.agent.AgentConsulClient.agentServiceRegister(AgentConsulClient.java:265)
	at com.ecwid.consul.v1.ConsulClient.agentServiceRegister(ConsulClient.java:304)
	at eu.orchestrator.agent.Agent.checkIfContainerServiceRunning(Agent.java:838)
	at eu.orchestrator.agent.Agent.phase6(Agent.java:296)
	at eu.orchestrator.agent.Agent.bootAgent(Agent.java:84)
	at eu.orchestrator.agent.Agent.main(Agent.java:69)
```

**Comment by smith3v** [comment]
@pparthenhs I can't help you with original issue. But it seems you just published the password for your database. I suggest you to rorate it with the new one.

**Comment by pparthenhs** [comment]
@smith3v thnx for the advice! I changed the password at the same time I published the issue!

**Comment by aleksandrserbin** [comment]
consul-api now uses `Script` field to create checks, from Consul doc:
`Args (array<string>) - Specifies command arguments to run to update the status of the check. Prior to Consul 1.0, checks used a single Script field to define the command to run, and would always run in a shell. In Consul 1.0, the Args array was added so that checks can be run without a shell. The Script field is deprecated, and you should include the shell in the Args to run under a shell, eg. "args": ["sh", "-c", "..."].`

@vgv, do we need compatibility with Consul versions below 1.0?

**Comment by vgv** [comment]
@pparthenhs 

Hi,

You should use `setTTL` instead of `setInterval`. 
This is kinda strange, but this is consul requirement, please see the docs - https://www.consul.io/api/agent/check.html

**Comment by vgv** [comment]
@aleksandrserbin 

Yes, I think I will add support for `Args` later

**Comment by aleksandrserbin** [comment]
Interval is also valid [option](https://github.com/hashicorp/consul/blob/57dd160f406a7422f21f3e01bf6ca2ad31815f6e/agent/structs/check_type.go#L52)

**Comment by aleksandrserbin** [comment]
Created [pull-request](https://github.com/Ecwid/consul-api/pull/172)
