### ISSUE TITLE
Urgent: Is there any endpoint like  /v1/agent/check/:checkid

### ISSUE THREAD

**Issue by gouthamkunduru90** [Ecwid/consul-api#178]
Urgent :I am trying to to get check details using check id but it is not working getting 404
tried endpoint GET /v1/agent/check/:checkid

is there anyway to get check based checkid?

**Comment by vgv** [comment]
No, consul doesn't have such endpoint – https://www.consul.io/api/agent/check.html

However, you can request all checks and filter it by checkId . Please take a look at ConsulClient.getAgentChecks() method

**Comment by vgv** [comment]
However, I see the new 'filtering' feature in consul which allows consul-client to return only particular checks.

I think I will implement it in near future.
