### ISSUE TITLE
HTTP Check

### ISSUE THREAD

**Issue by samuelalexanderg** [Ecwid/consul-api#18]
In Consul we can add Checks with HTTP and interval. 
But in this client, NewCheck does not provide the abitility to add checks based on HTTP.

https://www.consul.io/docs/agent/checks.html
Please add it

Also please provide me a sample to add HealthCheck for a service.

**Comment by vgv** [comment]
> Also please provide me a sample to add HealthCheck for a service.

I've add this example in main README file here - https://github.com/Ecwid/consul-api/blob/master/README.md

**Comment by vgv** [comment]
I've added HTTP to NewCheck, you can found this fix in consul-api 1.1.4
