### ISSUE TITLE
QueryParams waitTime and index should be long

### ISSUE THREAD

**Issue by chrismiller** [Ecwid/consul-api#2]
In the Consul code, QueryParams.waitTime is an int64 and QueryParam.index is a uint64. It's unlikely the waitTime being an int on the Java side will ever matter but the index being an int is a potential issue. With a busy and long-running Consul cluster an index might eventually exceed 2^31-1, at which point blocking requests will start returning immediately due to the mismatch between client and server.

In theory changing QueryParams.index to a long still doesn't solve the problem completely due to the signed/unsigned mismatch but the likelihood of an index ever getting high enough to matter would be extremely small. Checking for a negative index and writing the parameter as an unsigned value would solve that but I'm not sure it's worth the bother?

**Comment by vgv** [comment]
Sorry for long response delay, I was on vacation.

I think that we can forget about signed/unsigned mismatch right now and just convert all params to long. 
If long vs unsigned long will be a real problem in the future for real users we will fix it.
