### ISSUE TITLE
com.ecwid.consul.Util.generateUrl can generate malformed URLs

### ISSUE THREAD

**Issue by alexcorvino** [Ecwid/consul-api#20]
If a base url is passed into generateUrl with a trailing slash and a single URL parameter then the resulting URL will be malformed. 

For example, if ConsulClient.getKeyValues is called with a keyPrefix of "somefolder/somekey/" then the base URL generated by ConsulRawClient.makeGetRequest() is "http://localhost:8500/v1/kv/somefolder/somekey/". If the call to getKeyValues is from KeyValueConsulClient.getKVValues() then a URL parameter of "recurse" will be passed. 

In this case ConsulRawClient.makeGetRequest() will pass "http://localhost:8500/v1/kv/somefolder/somekey/" as a base URL and "recurse" as a parameter to
Util.generateUrl() which will return "http://localhost:8500/v1/kv/somefolder/somekey/?recurse" which Consul will always 404 on.

**Comment by vgv** [comment]
Which consul version do you use?
I've try your example on latest version (0.5.2) and both urls work great:
```
http://localhost:8500/v1/kv/somefolder/somekey?recurse
http://localhost:8500/v1/kv/somefolder/somekey/?recurse
```

**Comment by alexcorvino** [comment]
In coming back to this I rebuilt my project with the latest snapshot of spring-cloud-consul which uses 1.1.4 of consul-api. Something in one of those updates seems to have addressed the issue, so I'll close this. Thanks!
