### ISSUE TITLE
Is there a release coming soon?  Want gRPC support that is merged since 1.4.4

### ISSUE THREAD

**Issue by scaphe** [Ecwid/consul-api#204]
Hi,

Is there any chance of getting a fresh release soon.  I want to use the already merged code for gRPC health check support.

Thanks.

**Comment by spencergibb** [comment]
Spring Cloud users are also waiting on 1.4.5 https://github.com/spring-cloud/spring-cloud-consul/issues/625

**Comment by vgv** [comment]
Sure, I will release today

**Comment by vgv** [comment]
The 1.4.5 release is ready.
