### ISSUE TITLE
[Compatibility] [bug] 1.4.5 is breaking compatibility comparing to 1.4.2

### ISSUE THREAD

**Issue by eugeniyk** [Ecwid/consul-api#208]
https://github.com/Ecwid/consul-api/compare/384d96095b84c3f3a27dd3db5b037000215b844b...master

![image](https://user-images.githubusercontent.com/3932426/85252588-57cea800-b486-11ea-8f35-94da2b7314b0.png)

Consider bumping a major version

**Comment by vgv** [comment]
Yep, it was my mistake, sorry for that.
