### ISSUE TITLE
Support tokens in AgentClient

### ISSUE THREAD

**Issue by bpgray** [Ecwid/consul-api#22]
It would be helpful to support ACL tokens in AgentClient. Specifically, some consul deployments may require an application specific acl token to register/deregister services.

The pattern for providing a token exists in the KeyValueClient/KeyValueConsulClient, and the same pattern could be appropriate in the AgentClient.

Another approach would be to provide a default token in the ConsulRawClient, which would probably cover the majority of use cases.

**Comment by vgv** [comment]
Fixed in upcoming 1.1.5
