### ISSUE TITLE
exception error messages

### ISSUE THREAD

**Issue by a86c6f7964** [Ecwid/consul-api#26]
Whenever I log exceptions from this api there are no exception messages. I see 
```
! com.ecwid.consul.v1.OperationException: null
```
It would be nice to have a message that make sense, rather than having to catch the OperationException and read the statusCode and statusMessage off of it.

Also this help if I log ``exc.getMessage()`` which is helpful if you are logging a warning (because you are going to retry) and do not want to get the entire stack

P.S. on a semi relate note, is there a reason that the ConsulException is Runtime and not IO? I usually like to force people to catch exceptions rather than making them remember that this runtime exception could occur.

**Comment by edudar** [comment]
I second this request. I'm trying to figure out what's going on after 
```
com.ecwid.consul.v1.OperationException: null
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.setKVValue(KeyValueConsulClient.java:247) ~[consul-api-1.1.6.jar!/:na]
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.setKVValue(KeyValueConsulClient.java:235)
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.setKVValue(KeyValueConsulClient.java:220)
```
and it rather unclear...

**Comment by edudar** [comment]
I'm suggesting to put `rawResponse.content` as `exception.message` in #34. Consul provides quite reasonable messages in response. They are better than `500` status with `Internal Server Error` message that doesn't make things clearer.

**Comment by vgv** [comment]
I've merged PR, fixed
