### ISSUE TITLE
Support tokens for service deregister in AgentClient

### ISSUE THREAD

**Issue by bpgray** [Ecwid/consul-api#27]
Support to register services with tokens was added with:
https://github.com/Ecwid/consul-api/issues/22

It would also be helpful to support deregistering services with tokens

**Comment by bpgray** [comment]
Pull request open to add functionality: https://github.com/Ecwid/consul-api/pull/28

**Comment by bpgray** [comment]
Deregistration works fine without an ACL token in 0.5.2. Will reopen an issue/PR if this changes with the next version of consul.

**Comment by vgv** [comment]
> Will reopen an issue/PR if this changes with the next version of consul.

Thank you
