### ISSUE TITLE
Provide content of http response in exception

### ISSUE THREAD

**Issue by edudar** [Ecwid/consul-api#32]
I found that `OperationException` I was experiencing is related to invalid session id being passed to `/v1/kv?acquire=...`. Exception doesn't have such information and reads just like `OperationException{statusCode=500, statusMessage='Internal Server Error'}`. See https://github.com/hashicorp/consul/issues/1139 that consul actually responds with proper message which much more useful than standard HTTP error phrase.

**Comment by edudar** [comment]
PR #34

**Comment by vgv** [comment]
I've merged PR, fixed
