### ISSUE TITLE
Remove commons-logging

### ISSUE THREAD

**Issue by das-vinculum** [Ecwid/consul-api#36]
Hi,
we had problems using the api, because we had to explicitly remove commons-logging through an exclude, since it is bound to servlet-api in version 2.3. 

I removed it here https://github.com/rebuy-de/consul-api/tree/remove-commons-logging because I could not find any usage of it and the tests run well.

Am I missing something, otherwise I would create a pull request.

Regards

Florian

**Comment by vgv** [comment]
Hi

No need for pull request, I've just removed it

**Comment by das-vinculum** [comment]
thx
