### ISSUE TITLE
add socket/connection timeout defaults

### ISSUE THREAD

**Issue by a86c6f7964** [Ecwid/consul-api#40]
Currently the default socket/connection timeouts are undefined at best, likely infinity. I think that it could be good to set something sane for a default. If anyone is worried about this being a problem they could be set to something like 5 minutes. I doubt that anybody wants a request to consul to take greater than 5 minutes.

Currently these can be set by doing.
```java
final DefaultHttpClient httpClient = new DefaultHttpClient();
httpClient.getParams().setParameter(CoreConnectionPNames.CONNECTION_TIMEOUT, 30000);
httpClient.getParams().setParameter(CoreConnectionPNames.SO_TIMEOUT, 60000);
final ConsulRawClient consulRawClient = new ConsulRawClient("www.google.com", 81, httpClient);
final ConsulClient client = new ConsulClient(consulRawClient);
client.getKVBinaryValue("test")
```
I am using google port 81 because it will not respond to syn's and so will hang forever without the connection timeout set.

**Comment by a86c6f7964** [comment]
it would also be nice maybe to have a better api for setting those rather than having to build up a raw client. Maybe there could be a ConsulClient builder or something.

**Comment by vgv** [comment]
I've just added default timeouts right now (connect - 10s, read - 60s), without API extension via builders/additional constructors etc.
