### ISSUE TITLE
skip ssl certs verification through jvm arguments. 

### ISSUE THREAD

**Issue by manishrajkarnikar** [Ecwid/consul-api#52]
If consul is available only on https and if I don't want to verify the certs, looks like there is no way to override them. If there is please me know.

**Comment by vgv** [comment]
You can use your custom HttpClient with disabled cert checks and create ConsulClient like this:

```java
HttpClient customHttpClient = // setup your client and disable cert checks
ConsulRawClient rawClient = new ConsulRawClient(customHttpClient);
ConsulClient consulClient = new ConsulClient(rawClient);
```
