### ISSUE TITLE
How to aquire a value?

### ISSUE THREAD

**Issue by puradawid** [Ecwid/consul-api#55]
Hi, I am trying to implement [leader election][1] using this client and I can find aquiring method:

    curl -X PUT -d <body> http://localhost:8500/v1/kv/<key>?acquire=<session>

Can I do it somehow?

[1]: https://www.consul.io/docs/guides/leader-election.html

**Comment by puradawid** [comment]
Should be closed:

> Aquiring value is done by setKV and providing PutParams object.

**Comment by vgv** [comment]
> Aquiring value is done by setKV and providing PutParams object.

Yep :)
