### ISSUE TITLE
Allow specifying ACL token to getCatalogServices()

### ISSUE THREAD

**Issue by sirlatrom** [Ecwid/consul-api#56]
Though apparently undocumented, it is possible, at least in consul 0.6.0, to specify a `?token=<ACL-token>` query parameter on the endpoints `/v1/catalog/services` and `/v1/catalog/service/<service>`.

Consider this situation: If the "anonymous" token has the following policy (which I'm aware disables DNS discovery, but we're not using that where I work):

```hcl
service "" {
  policy = "deny"
}
```

... then snooping individuals will not be able to list registered services and their IP addresses and port numbers. Meanwhile, a client with a different ACL token which provides a policy like the following will be successfully able to list the registered services:
```hcl
service "" {
  policy = "read"
}
```

With a setup like the above, it would be very useful indeed to be able to provide an ACL token to the `ConsulClient#getCatalogServices()` and various `ConsulClient#getCatalogService()` methods, which would then be passed as a query parameter to the `/v1/catalog/services` and `/v1/catalog/service/<service>` endpoints, respectively.

**Comment by vgv** [comment]
Fixed in #61
