### ISSUE TITLE
OperationException does not propagate statusCode/statusMessage to exception message

### ISSUE THREAD

**Issue by ahawtho** [Ecwid/consul-api#65]
It would help troubleshooting if OperationException passed information to the super class constructor taking a 'message'.  Otherwise, if there is an exception, we don't get any context about the failure in logs, etc..

**Comment by pjvds** [comment]
Is there any reason this fix is not released yet?

**Comment by vgv** [comment]
@pjvds 
I've released the new version 1.2.0 today

**Comment by pjvds** [comment]
Awesome @vgv, is there any easy way to add nightly or continuous builds? We could setup a travis, codeship, or whatever CI service. What are your thoughts?
