### ISSUE TITLE
Release Notes/Tags

### ISSUE THREAD

**Issue by jimmywan** [Ecwid/consul-api#68]
Any chance we can get release notes and have the releases tagged in github?

**Comment by vgv** [comment]
Sure.
You can find the latest releases here - https://github.com/Ecwid/consul-api/milestones

**Comment by jimmywan** [comment]
I meant on here:
https://github.com/Ecwid/consul-api/releases
or here:
https://github.com/Ecwid/consul-api/tags
But I suppose that will work.

**Comment by petergardfjall** [comment]
I think this issue should be re-opened. There is no way of tracing a particular release downloaded from maven central back to its source at this time.

**Comment by vgv** [comment]
Hi,

Guys, now I understand that you are talking about. Current release (1.4.3) and all next will be tagged and released via GitHub Tags/Releases feature.
