### ISSUE TITLE
Accessing consul behind a proxy

### ISSUE THREAD

**Issue by rubms** [Ecwid/consul-api#77]
Consul instances behind a proxy may have a different application path. For example: http://server:8000/**consul**/v1/kv/...

If a consul instance behind a proxy, that has a different application path, needs to be accessed with consul-api it will not be possible to configure the necessary consul URL given the current set of constructors in ConsulClient. A constructor accepting the base application path is needed.

**Comment by vgv** [comment]
I've merged the PR
