### ISSUE TITLE
Add support for `near` queryparam

### ISSUE THREAD

**Issue by dgreene-r7** [Ecwid/consul-api#82]
The `/v1/catalog/service/<service>` endpoint supports a `near` query parameter that
> will sort the node list in ascending order based on the estimated round trip time from that node. Passing "?near=_agent" will use the agent's node for the sort.

**Comment by juergdrollinger** [comment]
Exactly this feature I miss.
Or simply to pass any UrlParameters instead of QueryParams

**Comment by vgv** [comment]
merged #90
