### ISSUE TITLE
Prepared queries

### ISSUE THREAD

**Issue by asmabri** [Ecwid/consul-api#91]
Add support for the prepared queries API https://www.consul.io/docs/agent/http/query.html

**Comment by benhass** [comment]
Hey @vgv, is this on the roadmap? If not, would you accept a PR adding basic support for the `GET /query/:uuid/execute` endpoint? https://www.consul.io/api/query.html#execute-prepared-query

**Comment by vgv** [comment]
Hi @benhass 

I plan to implement it in next couple of months. Sure, I will accept your PR if you want to do it by your own
