### ISSUE TITLE
Why there is no API to register `shell` check with new service ?

### ISSUE THREAD

**Issue by manjunathshetty** [Ecwid/consul-api#93]
NewService.Check doesnt have any method to add shell checks. I want to add something like this while registering the service

"checks":[
    	{
    	"shell": "echo '' | nc host 0100 || exit 2",
    	"interval": "20s"
    	}
    ]

Is there any other way to register shell based checks ?

**Comment by pwielgolaski** [comment]
I think you are talking about script from https://www.consul.io/docs/agent/checks.html
and it can be set by https://github.com/Ecwid/consul-api/blob/master/src/main/java/com/ecwid/consul/v1/agent/model/NewService.java#L36

**Comment by vgv** [comment]
Yep, you can register shell check like this:

```
NewService.Check check = new NewService.Check();
check.setInterval("30s");
check.setScript("/bin/somescript");

NewService newService = new NewService();
newService.setName("test-service");
newService.setCheck(check);
consulClient.agentServiceRegister(newService);
```
