### ISSUE TITLE
Trying to use TLSConfig and https connection - httpclient methods deprecated

### ISSUE THREAD

**Issue by lpmontx** [Ecwid/consul-api#96]
Not just deprecated but no longer functional. Throws UnsupportedOperationException

In DefaultHttpsTransport the call to getSchemeRegistry().   That Apache code has:

       throw new UnsupportedOperationException()   because of deprecation

FROM: DefaultHttpsTransport 
Scheme sch = new Scheme("https", sf, tlsConfig.getSslPort());
this.httpClient.getConnectionManager()**.getSchemeRegistry()**.register(sch);  // results in UnsupportedOperationException

**Comment by javahas** [comment]
Did you find workaround?

**Comment by lpmontx** [comment]
I have a modified DefaultHttpsTransport class that is working with TLS.  I am attaching it.   I have not spent enough time on it to verify this is the optimal solution.  Instead of extending the abstract class I implemented this package's HttpTransport.
[DefaultHttpsTransport.java.txt](https://github.com/Ecwid/consul-api/files/1042505/DefaultHttpsTransport.java.txt)

**Comment by javahas** [comment]
Thanks!:) I ended up using ConsulRawClient worked as well.
consulClient = new ConsulClient(new ConsulRawClient(consulHost, consulPort, getHttpClient()));

**Comment by vgv** [comment]
I've merged the PR
